# Generated by Django 5.2.17 on 2026-08-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_medium_scale_expansion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationdraft",
            name="schema_version",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
